# Generated by Django 2.2 on 2019-04-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20)),
                ('skills', models.TextField()),
                ('counters', models.TextField()),
                ('side', models.TextField()),
            ],
        ),
    ]
