# Generated by Django 2.2 on 2019-04-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siegeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siege',
            name='faction',
            field=models.TextField(default='FBI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='gadget',
            field=models.TextField(default='GL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='equipment',
            field=models.TextField(default='Smoke'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='armor',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='speed',
            field=models.TextField(default='3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='counters',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='side',
            field=models.TextField(default='ATK'),
            preserve_default=False,
        ),
    ]
