# Generated by Django 4.0.4 on 2022-06-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siegeapi', '0002_auto_20190419_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siege',
            name='armor',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='siege',
            name='speed',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
