# Generated by Django 4.0.4 on 2022-06-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siegeapi', '0003_alter_siege_armor_alter_siege_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siege',
            name='skills',
        ),
    ]
