# Generated by Django 4.0.4 on 2022-06-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siegeapi', '0004_remove_siege_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='siege',
            name='count1',
            field=models.TextField(default='operator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='count1p',
            field=models.TextField(default='counter description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='count2',
            field=models.TextField(default='operator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='count2p',
            field=models.TextField(default='counter description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='equip1',
            field=models.TextField(default='Smoke'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='equip2',
            field=models.TextField(default='Breach'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='weap1',
            field=models.TextField(default='Weapon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='weap2',
            field=models.TextField(default='Weapon2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='weapons',
            field=models.TextField(default='Weapons'),
            preserve_default=False,
        ),
    ]
