# Generated by Django 4.0.4 on 2022-06-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siegeapi', '0005_siege_count1_siege_count1p_siege_count2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siege',
            old_name='weap1',
            new_name='prim1',
        ),
        migrations.RenameField(
            model_name='siege',
            old_name='weap2',
            new_name='prim2',
        ),
        migrations.AddField(
            model_name='siege',
            name='prim3',
            field=models.TextField(default='Weapon3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='secon1',
            field=models.TextField(default='Sidearm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siege',
            name='secon2',
            field=models.TextField(default='Sidearm2'),
            preserve_default=False,
        ),
    ]
