# Generated by Django 4.0.4 on 2023-03-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siegeapi', '0006_rename_weap1_siege_prim1_rename_weap2_siege_prim2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siege',
            name='release',
            field=models.TextField(default='Base'),
            preserve_default=False,
        ),
    ]
