# Generated by Django 4.0.4 on 2023-04-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siegeapi', '0007_siege_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siege',
            name='counters',
        ),
        migrations.RemoveField(
            model_name='siege',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='siege',
            name='weapons',
        ),
    ]
