# Generated by Django 4.0.4 on 2022-07-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siegeapi_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateField(blank=True, default='2101-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateField(blank=True, default='2101-01-01'),
        ),
    ]
